//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code923.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Copyrights
    {
        public System.Guid Copyrights_Id { get; set; }
        public string Copyrights_Title { get; set; }
        public string Copyrights_Details { get; set; }
        public string Copyrights_Tel { get; set; }
        public string Copyrights_Mobile { get; set; }
        public string Copyrights_QQ { get; set; }
        public string Copyrights_QQ2 { get; set; }
        public string Copyrights_Email { get; set; }
        public string Copyrights_Logo { get; set; }
        public string Copyrights_Image { get; set; }
        public string Copyrights_Address { get; set; }
    }
}
