//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code923.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hxsd_DbEntities : DbContext
    {
        public hxsd_DbEntities()
            : base("name=hxsd_DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Copyrights> Copyrights { get; set; }
        public virtual DbSet<FriendShips> FriendShips { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Seos> Seos { get; set; }
        public virtual DbSet<SystemMenus> SystemMenus { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersPermissions> UsersPermissions { get; set; }
        public virtual DbSet<WebMenus> WebMenus { get; set; }
    }
}
