//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code923.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebMenus
    {
        public System.Guid WebMenus_Id { get; set; }
        public string WebMenus_Title { get; set; }
        public string WebMenus_Link { get; set; }
        public Nullable<System.Guid> WebMenus_ParentId { get; set; }
        public string WebMenus_Icon { get; set; }
        public Nullable<int> WebMenus_DeleteId { get; set; }
        public System.DateTime WebMenus_CreateTime { get; set; }
        public System.DateTime WebMenus_UpdateTime { get; set; }
    }
}
